// Generated by `bun init`

declare module "*.svg" {
    /**
     * A path to the SVG file
     */
    const path: `${string}.svg`
    export = path
}

declare module "*.module.css" {
    /**
     * A record of class names to their corresponding CSS module classes
     */
    const classes: { readonly [key: string]: string }
    export = classes
}

declare module "bun" {
    interface Env {
        GOOGLE_CLOUD_CLIENT_ID: string
        GOOGLE_CLOUD_CLIENT_SECRET: string
    }
}
